clone_depth: 10
skip_tags: true

init:
  - git config --global core.autocrlf input

branches:
  only:
    - deploy

environment:
  SIGNTOOL_PATH: 'C:/Program Files (x86)/Microsoft SDKs/Windows/v7.1A/Bin/SignTool.exe'
  SIGN_WIN_CERTIFICATE_FILE: 'C:/foss_ar_sha2.pfx'
  SIGN_WIN_CERTIFICATE_PASSWORD:
    secure: jZHktkydPALqcwx36cBY1g==
  AWS_ACCESS_KEY_ID:
    secure: un4e1Apf/PIHv/duLtXtk4j4AIgorOKxvMhxhoUd4N8=
  AWS_SECRET_ACCESS_KEY:
    secure: zP4aGkRtRqZIKZ2tM2q//6dC4SfzKdxDBGTSV3AEbpUnDDco/uMy9ZU1cmVEQigk
  GITHUB_TOKEN:
    secure: VgebEox3uOMipNS2O/GeWXLpfqPcIp3hUstSLsaL0YpHvxG95FVzQLuI3IbahvFH

cache:
  - "node_modules -> package.json"
  - "src\\node_modules -> src\\package.json"
  - "cache -> src\\package.json"
  - "%APPDATA%\\npm-cache"

install:
  - npm install -g npm@3
  - set PATH=%APPDATA%\npm;%PATH%
  - aws s3 cp --region eu-west-1 s3://aluxian/certificates/foss_ar_sha2.pfx C:/foss_ar_sha2.pfx
  - npm install -g gulp
  - npm install

before_build:
  - npm test
  - gulp rebuild:32 --verbose

build_script:
  - gulp pack:win32:portable --prod --verbose
  - gulp pack:win32:installer --prod --verbose

deploy_script:
  - gulp clean:prev-releases:win32 --verbose
  - gulp publish:github --verbose

artifacts:
  - path: dist\*
